interfaces:
  - name: "loopback0"
    ip: "1.1.1.1"
    mask: "255.255.255.255"
  - name: "eth0/1"
    ip: "12.1.1.1"
    mask: "255.255.255.0"
asn: 65001
loopback0: "1.1.1.1"
bgp_neighbors:
  - ip: "2.2.2.2"
    asn: 65002
static_routes:
  - network: "2.2.2.2"
    netmask: "255.255.255.255"
    next_hop: "12.1.1.2"