---
- name: Running Show Commands on Cisco IOS
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Display show version output
      debug:
        var: show_version_output.stdout_lines[0]